import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import Navbar  from '../components/Navbar/Navbar'
import {Container} from '@mui/material'
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>poolesville_hacks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
        <Navbar/>
      <main>
         
 
      </main>

    </>
  )
}

export default Home
