import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from "../styles/Home.module.css"
import Navbar  from '../components/Navbar/Navbar'
import {Container, Typography, Button} from '@mui/material'
const Home: NextPage = () => {
  return (
      <>
          <Head>
              <title>poolesville_hacks</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
          <Navbar />
          <main>
              <Container
                  sx={{
                      height: "40vh",
                      minHeight: 400,
                      display: "flex",
                      flexDirection: "column",
                      justifyContent: "center",
                      alignItems: "flex-start",
                      
                      gap: "15px"
                  }}
              >
                  <Typography component="h1" variant="h3">
                      poolesville_hacks
                  </Typography>
                  <Button color="secondary" variant="contained">
                    Learn More
                  </Button>
              </Container>
          </main>
      </>
  );
}

export default Home
